fail_fast: false
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black #TODO: add check_only
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --check-only --diff --stdout .
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [python]